version: 2.1

orbs:
  unity: game-ci/unity@1.7.0
  win: circleci/windows@2.4.1
jobs:
  inno-setup:
    executor:
      name: win/default
    steps:
      - attach_workspace:
          at: '.'
      - run: choco install innosetup
      - run: ls 
      - run: ls /
      - run: iscc.exe build/installer.iss
      - store_artifacts:
          path: build/xgolf_setup.exe
  unity-build:
    executor:
      name: 'unity/windows-2019'
      size: 'medium'
      editor_version: '2019.4.35f1'
      target_platform: 'windows-il2cpp'
    steps:
      - checkout
      - unity/prepare-env:
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-username-var-name: UNITY_USERNAME
          unity-password-var-name: UNITY_PASSWORD
          no_output_timeout: '30m'
      - unity/build:
          step-name: 'Build StandaloneWindows64 il2cpp'
          build-target: StandaloneWindows64
          build-method: 'XGolf.Build.XGolfBuild.BuildGame'
          build-name: 'XGolf'
          store-artifacts: false
          compress: true
          persist-to-workspace: true
          custom-parameters:
            '-VERSION=$VERSION -ENV=$ENV -API_URL=$API_URL -SIMULATOR_EMAIL=$SIMULATOR_EMAIL -SIMULATOR_PASSWORD=$SIMULATOR_PASSWORD'
  unity-test:
    executor:
      name: 'unity/windows-2019'
      size: 'medium'
      editor_version: '2019.4.35f1'
      target_platform: 'windows-il2cpp'
    steps:
      - checkout
      - unity/prepare-env:
          unity-license-var-name: UNITY_ENCODED_LICENSE
          unity-username-var-name: UNITY_USERNAME
          unity-password-var-name: UNITY_PASSWORD
          no_output_timeout: '30m'
      - unity/test:
          step-name: 'Check if the tests run and results are uploaded'
          test-platform: 'editmode'

workflows:
  
  build-and-test:
    jobs:
      # - unity-test:
      #     name: 'unity-test'
      #     context: 
      #       - unity
      # - unity-build:
      #     requires:
      #       - unity-test
      #     context: 
      #       - unity
      #       - simulator-stage
      #     filters:
      #       branches:
      #         only:
      #           - dev
      #           - circle-ci
      - unity-build:
          # requires:
          #   - unity-test
          context: 
            - unity
            - simulator-prod
          filters:
            branches:
              only:
                - main
      - inno-setup:
          requires:
            - unity-build
          context:
            - simulator-prod
          
        