using UnityEngine;

namespace XGolf.Service
{
    [CreateAssetMenu(fileName = "ENV", menuName = "Env Variable")]
    // This should be placed in Resource.
    // This will be also generated by Build pipeline
    public class EnvConfig : ScriptableObject
    {
        public string ENV;
        public string API_URL;
        public string SIMULATOR_EMAIL;
        public string SIMULATOR_PASSWORD;
    }
}